services:
  nginx-server:
    image: nginx:1.28.0-otel
    container_name: nginx-server
    ports:
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/entrance.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/server_1.conf:/etc/nginx/conf.d/default.conf
      - /var/log/notes/nginx:/var/log/nginx
      - .:/web
    restart: unless-stopped